name: Check Package Version in PR

on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/snap/src/**'

jobs:
  check_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'create-main-branch'
        run: 'git branch --track main origin/main'

      - name: Get version from main branch
        id: get_version_main
        run: echo "::set-output name=version::$(git show HEAD~1:package.json | grep '"version":'  | cut -d '"' -f 4)"

      - name: Get version from PR branch
        id: get_version_pr
        run: echo "::set-output name=version::$(grep '"version":' package.json | cut -d '"' -f 4)"

      - name: Compare versions and prevent merging if the same
        run: |
          if [ "${{ steps.get_version_main.outputs.version }}" == "${{ steps.get_version_pr.outputs.version }}" ]; then
            echo "Error: Versions in main branch and PR are the same - please upgrade version in PR."
            exit 1
          else
            echo "Versions are different, allowing merge"
            echo "::set-output name=version_changed::true"
          fi
